var engMap={
"3h41wkxj": "Sign in",
"c7folydq": "Home",
"rf7r2nk0": "LOGIN",
"g143uz7d": "Password",
"cais5tw0": "Email or Username",
"gs8awxej": "Sign into",
"no_security_found": "No security found",
"no_doc_found": "No document found",
"no_proposals_found": "No proposal found",
"zlksaikw": "your",
"lex9mep0": "account",
"d9hhr78b": "account",
"e9zrlew0": "account",
"zdbe1lx9": "account",
"1tt86su5": "your",
"y8llhhe3": "Home",
"r5la6ony": "BBC News",
"rog3ydmc": "@bbc",
"y1dolub7": "Home",
"4kyuvn3o": "Upload Document",
"him7gi6o": "File",
"lh2w6q42": "SELECT ",
"mpbhr71m": ".",
"jzvxxaxu": "Click to upload your document",
"mw4a4y0a": "Description",
"alsw67uc": "Document's description",
"3hz1whes": "Upload",
"c7ypx4h2": "Home",
"h66hylfo": "Notifications",
"dlkgtx0t": "Proposal",
"lq59qmsn": "Schedule Appointment",
"0lw6g9ud": "Type new message",
"95k73u5g": "Home",
"p1nsrsd1": "__",
"yot02jf2": "Change Password",
"510yg9y6": "Current password",
"729kp7ui": "Your current password",
"ju5jgv6f": "Invalid password",
"2l6qayo4": "New password",
"oef8jq9l": "New password",
"gtihat6e": "New password needs at least 6 characters",
"lz5cj3qp": "Confirm new password",
"lph5tz72": "Confirm your new password",
"y6byl3gh": "Confirm new password must match new password",
"iy4dy5qk": "Change password",
"nfc91a9j": "Home",
"english": "English",
"arabic": "Arabic",
"vietnamese": "Vietnamese",
"12cgqet1": "Proposal",
"j0hr735r": "DECLINE",
"acceptable_formats": "Acceptable formats",
"f8pf4flh": "Accept",
"vhohm2gh": "Declined at",
"0gxshjqc": "Accepted at",
"lw93ftpw": "Home",
"ytd2avxs": "Home",
"57k3dgbt": "SVG",
"f56350tm": "SVG Compiler",
"yux64vyf": "Example 2",
"m89f6pjw": "Tab View 2",
"0f4cc5jv": "Example 3",
"ow2th2ka": "Tab View 3",
"7b4df5uj": "Page Title",
"m5iym6ry": "Home",
"j2jcor2x": "Home",
"preview": "Preview",
"fill_in": "Fill in",
"download": "Download",
"signature": "Signature",
"xptnvk4d": "Home",
"lvtq8f1d": "Transaction type*",
"mzy7ssrc": "Alt. Investment",
"eq4x9n1u": "Cash Deposit",
"cxoslr35": "Cash Withdraw",
"ggeo4b0j": "Clearing Fee",
"z3seosat": "Transaction status*",
"u6kp9mh5": "Pending",
"mk5ongux": "Executed",
"h5kwz5n8": "Failed",
"airvu3wg": "Currency*",
"l0lwzjgx": "USD - US Dollar",
"1183o2jn": "VND - Vietnamese Dong",
"b2wletq2": "THB - Thai Baht",
"f52mzh01": "JPY - Japanese Yen",
"4ozeqrcz": "Search for an item...",
"cbvxrrgx": "Amount*",
"22c25jl6": "Amount must be greater than 0",
"n2u1440v": "USD \$",
"wbwyrgib": "Open rate",
"oba6y3ps": "USD/USD",
"e0lclrlh": "Transaction Date*",
"b2ene7pk": "Date must be specified",
"l33tyaq2": "Accounting Date",
"580q4cpd": "Value Date",
"3gltw1as": "Client Settlement",
"8z8om63p": "Select...",
"7qfeihe1": "su",
"dakksbhl": "HCM City",
"609fatzr": "Search for an item...",
"cmvhpvxy": "Company Settlement",
"dsiy2ndn": "Select...",
"e22smxml": "su",
"hlx823un": "HCM City",
"vrkibydv": "Search for an item...",
"ylem5knl": "Broker/Counterparty Settlement",
"ks86zlgi": "Select...",
"yvdx9x5p": "su",
"cnko6piz": "HCM City",
"5zbutpiz": "Search for an item...",
"j9fxzxjx": "Notes",
"zc9jp3sw": "Create Contact Report",
"omnyycbo": "Generate & Save Invoice",
"qsuxqtdi": "Invoice number",
"2gprp57y": "Invoice currency",
"u9zuq2tq": "USD - US Dollar",
"2o1zdp3v": "VND - Vietnamese Dong",
"g4zhlylb": "THB - Thai Baht",
"oquoet9p": "JPY - Japanese Yen",
"cm03jx79": "Search for an item...",
"devm6cmv": "Add Fee / Tax",
"w3yrqad9": "Create",
"rfeltbti": "Home",
  "z97rvm72": "New Trade",
  "ixctvaic": "Portfolio",
  "53dk25lw": "Buy to Open",
  "6df6xxpt": "Buy to Close",
  "81dcf4qa": "Sell to Open",
  "lzd9cyr1": "Sell to Close",
  "cjuvvsm5": "Incoming Transfer",
  "zx1wc2ro": "Outgoing Transfer",
  "m7418olr": "Search for transaction type",
  "rumkikc1": "Name, ISIN, FIGI or Ticket",
  "dmgzjo53": "Security's name must be given",
  "whkrwls1": "Type",
  "lmnve4ua": "Buy to Open",
  "kxq6qy7f": "Buy to Close",
  "zrj8fd7n": "Sell to Open",
  "98cdg04u": "Sell to Close",
  "isbfun57": "Incoming Transfer",
  "zswpadhe": "Outgoing Transfer",
  "catj4e9j": "Search for transaction type",
  "7fx237xy": "Time In Force",
  "f2fyvhfy": "Date must be specified",
  "2mpa9jiq": "Notes",
  "u7hyldvt": "Order Type",
  "2odrp5sn": "Quantity",
  "lz424u11": "Current Price",
  "bhxqgsuw": "USD \$",
  "q9p7fv0r": "Limit Price",
  "ee6858r7": "USD \$",
  "nbthbjny": "USD \$",
  "4noemhfd": "Amount",
  "n25ml3i7": "USD \$",
  "h2vfcolj": "TRANSMIT",
  "7orhqoys": "Home",
  "want_to_logout": "Are you sure you want to logout?",
  "transaction_created": "Transaction created successfully.",
  "7r8yq7mw": "Status",
  "communication_support": 'Authorization code 721864 to communicate to support',
  "dlgf18jl": "Document",
  "mg8sso38": "Sign",
  "5tjloy3c": "Rejected at",
  "rejected": "Rejected",
  "ktrsz8sp": "Accepted at",
  "9f0ag6b2": "Home",
  "fklubmeg": "Transfer Funds",
  "pjltxv8v": "Transfer type",
  "v2r1dlh4": "Internal Transfer",
  "trd84dis": "External Transfer",
  "d5n27mwd": "ACH Payment",
  "sut6gbhe": "Transfer Type",
  "ks1k9ld0": "Account",
  "at0kn69v": "Select Account",
  "9h7dbdxv": "Account ****2010",
  "mo20dtfv": "Account ****2011",
  "m4lj06oh": "Account ****2012",
  "hg4nab9x": "Choose an Account",
  "drpnsezr": "Amount",
  "mikxtr7z": "Your current balance:",
  "69029o9e": "\$7,630",
  "9vu9xcur": "Or",
  "szvozgsg": "Scan Payment",
  "1mpq4mv4": "Send Transfer",
  "umwc3lc6": "Home",
  "cnc2a7kn": "CHANGE LANGUAGE",
  "yi7h9iqo": "Apply",
  "tox2fkuw": "Home",
  "kls2a0ck": "Home",
  "ovw4ksp4": "Term of Service",
  "sb815feb": "Privacy Policy",
  "l6rxib8x": "I've read and agree to the ",
  "zfszy2xl": "Term of Service",
  "x0c3ht3x": " and ",
  "lnywo5pe": "Privacy Policy",
  "8lqdtz8h": "Accept",
  "vpe2dnt0": "Home",
  "nx64605t": "Home",
  "apuqhrbh": "Please confirm",
  "c4m8fcp2": "Reject",
  "e1wyk8ql": "Accept",
  "nkc71403": "Security Name",
  "xc0jtpk9": "Status",
  "j72npzob": "Type",
  "fyy6awn3": "Portfolio Name",
  "qwicoekk": "Security Name",
  "691qwpww": "Quantity",
  "xopvpm3o": "Price",
  "pgdm3cxj": "Amount",
  "yx8usjux": "Trade Date",
  "75vcm9jx": "Type",
  "yow754bx": "Advisor",
  "c1i8ilcn": "We believe you are over allocated in GE and are better suited to diversify into technology sector.",
  "y4rezelu": "ADDITIONAL, COMMENTARY FROM ADVISOR",
  "1wdyw1a0": "We've gotten word that GE is about to post a bad quarter, so we recommend you sell your position and pick up more Apple",
  "99qsbuko": "Last update",
  "ke604v9b": "READ PROPOSAL",
  "prtogarh": "I read the documents and agree to the terms of the proposal",
  "decline_proposal": "Decline Proposal ?",
  "accept_proposal": "Accept Proposal ?",
  "3esw1ind": "ACCEPT",
  "a7lwigx2": "Declined at",
  "uolmr1cx": "Accepted at",
  "s1juvlo2": "OR",
  "fbk0uba7": "Call your advisor",
  "pkkj5rta": "Chat with your advisor",
  "chat": "Chat",
  "dperp1f4": "Schedule appointment",
  "mlj5814u": "PROPOSAL",
  "sd43hio2": "Schedule Appointment",
  "rkobqzvw": "Home",
  "uak0wsex": "Portfolio",
  "eg1yw963": "Transactions",
  "1vddbh59": "DOCUMENTS",
  "0po64aet": "Proposal",
  "hello": "Hello! How can I assist you?",
  "jmpup8vw": "Home",
  "u9g83xki": "Home",
  "mdc6xyu6": "Portfolio",
  "4ihsur3q": "Portfolio",
  "d33p2mgm": "Market",
  "khwv42ow": "Document",
  "wux5rc10": "Document",
  "5u97oz1q": "Proposal",
  "6kq446fx": "Proposal",
  "ran9xdwl": "POPULAR",
  "lwqxf341": "No News Today",
  "gln3vyrv": "RECOMMENDED",
  "g2rxi1c1": "Favourite selection",
  "yiyjkffh": "REFRESH",
  "yj6g8w9q": "Swipe left",
  "35ozpi3w": "Swipe right",
  "pzvyvrig": "Portfolio",
  "l0x6h75l": "No Portfolio Found",
  "1ozb665k": "No portfolio found",
  "1ixt6js5": "Transaction",
  "n93guv4x": "All",
  "5xbdmla8": "Portfolio 1",
  "ojyp5aek": "Porfolio 2",
  "dmr0x7ur": "Porfolio 3",
  "uv5le3hr": "Porfolio's name",
  "u52470kh": "No Transactions Found",
  "449komyb": "No Transactions Found",
  "lt49c1mu": "Proposal",
  "t7tz8m1x": "A-Z",
  "lkq0botg": "Z-A",
  "wdlmnbeh": "Newest",
  "gxc8dzyc": "Oldest",
  "r3f0hrjr": "Search for an item...",
  "93z66pdg": "Document",
  "0c3w378f": "Rejected at ",
  "c64nnx2a": "Accepted at ",
  "b4bbsw9r": "Document",
  "gedmceci": "A-Z",
  "7ifi5rzq": "Z-A",
  "100mebqo": "Newest",
  "f92uq3rg": "Oldest",
  "h4estl7l": "Search for an item...",
  "qsv6jc1u": "Upload",
  "zu3zuhvo": "Confirm?",
  "s1jcpzx6": "CANCEL",
  "bdc48oru": "CONFIRM",
  "tea2m5lq": "Allocation",
  "e0dy1vxx": "ROI",
  "4kttzprb": "Name",
  "6thwwafn": "ISIN",
  "ivu9tdzj": "Currency",
  "fbgy82bc": "Last Price",
  "swv2ctiz": "Cost Price",
  "cdklrlbv": "ROI",
  "ox3fj6xq": "Quantity",
  "juhk5a4f": "Amount",
  "xai3n31z": "Allocation",
  "qhszshsn": "Position as of",
  "zjpj3rb3": "A-Z",
  "qdw51x3q": "Z-A",
  "rp3i5rcp": "Newest",
  "agree_checkbox": "Please check the checkbox first",
  "5dpmi95h": "Oldest",
  "9j789sh8": "Search for an item...",
  "yfas6pma": "Filter options",
  "filter": "FILTER",
  "sort": "SORT",
  "xccshnlg": "Accounts",
  "nhu5w9hh": "All Accounts",
  "rfz2zg29": "Account 1",
  "e8wn77rc": "Account 2",
  "kwzaqasj": "Account 3",
  "ip67vees": "Search for an account",
  "bzc91fwt": "File name",
  "oxhc1io0": "",
  "1mrmlye5": "",
  "4n2ah71g": "Types",
  "date_in_range": "Date in range",
  "62i1ajo9": "All",
  "1bjf87l7": "Document",
  "6ihgprib": "Form",
  "lhntzq4q": "Package",
  "6b02yqcj": "Search for an item...",
  "wy8o7ldl": "From",
  "79c9j9tz": "Filter options",
  "uvch601w": "Advisor",
  "52i8slyz": "",
  "58gmka4m": "",
  "rvrrcr87": "Proposal name",
  "select_file": 'Select File',
  'capture_image': 'Capture Image',
  "3lusoo7q": "",
  "48bz3ofm": "",
  "tl67wc2i": "Types",
  "ti52gke6": "All",
  "stsemzk4": "New Buy",
  "6p82d124": "Suggest Sell",
  "i76kvnmi": "Search for proposal type...",
  "7hue4ywl": "From",
  "lyqt7dgr": "To",
  "g7rr5vmv": "CLEAR",
  "lmndaaco": "APPLY",
  "dx3hqly7": "Transaction as of",
  "prsblk0u": "Market",
  "wzls4zjf": "Type security name",
  "7v8svtoq": "NEW TRANSACTION",
  "1p01lh7n": "Asset Class",
  "q1rji7uu": "All",
  "0j3ikcyz": "Alternative Investment",
  "2wib8de2": "Bond",
  "ub3zx1xd": "Cfd",
  "47ohy39v": "Collectible",
  "sotc1ho8": "Search for an asset class",
  "zfneqwjq": "Industry",
  "d63k4veh": "All",
  "hvikpfj5": "Industrial",
  "dv5qr0ef": "Health Care",
  "kwbxaj2d": "Consumer services",
  "8f8r6kpl": "Ultilities",
  "8ltvrr9u": "Search for an industry",
  "nkjefkra": "Currency",
  "9kbotd9v": "All",
  "3wp2osm7": "AED - Emirati Dirham",
  "dnclvhao": "USD - US Dollar",
  "2i05dwg2": "VND - Vietnamese Dong",
  "ng4uvnyc": "Search for a currency",
  "jc3m5lbr": "From",
  "ww0vqchu": "To",
  "lafovd94": "Apply",
  "fiha8uf5": "Home",
  "p38uhcf6": "Home",
  "xn2nrgyp": "Portfolio",
  "portfolio_msg": "Please select the portfolio",
  "limit_price_msg": "Please enter the limit price",
  "new_order": "NEW ORDER",
  "more": "More",
  "a850huyh": "Portfolio",
  "nkifu7jq": "Proposal",
  "32ibm5x3": "Proposal",
  "w5wtcpj4": "Profile",
  "e9g2ybjp": "Profile",
  "5pxwycp5": "Notification",
  "v9vw92bm": "Profile",
  "slptsuin": "Market",
  "d696b0mg": "New Trade",
  "nqqw2mxy": "Transfer",
  "ba57jiqz": "Upload",
  "13mzcnly": "Documents",
  "o5wm04m6": "MARKET",
  "t2nv4kvj": "UPLOAD",
  "acyeoaaw": "PORTFOLIO HEALTH CHECK",
  "dxc8grzt": "Suitability",
  "3vkimctv": "Appropriateness",
  "2gjb3gie": "Login Verification",
  "4odbxp9t": "Please input the code to continue",
  "4jp9h6pq": "Please confirm that your authentication application is working by entering a generated code below",
  "u6n47sl4": "Verifying...",
  "v5jx3zzx": "Didn't receive any code?",
  "dumdc5yp": "Resend",
  "efkolajb": "MINOR ISSUE",
  "05djgw4o": "MAJOR ISSUE",
  "834hxg71": "Not checked",
  "bwcpcgd0": "The following investments are not in line with your financial knowledge.",
  "zz2ivcgu": "No issues have been detected.",
  "83o1ghax": "NET VALUE",
  "hdgv1exn": "Date",
  "cm2ob3q4": "Net Value",
  "y6z0kvbz": "Portfolio Value",
  "57fz6g1m": "Amount Invested",
  "rpfp7xvs": "Cash Available",
  "zomhasya": "Performance",
  "7h0zeqv0": "Asset Class",
  "o00oeypg": "Currency",
  "6u2u1x9z": "Health Alerts",
  "2um0eu09": "Detail",
  "kc4yx2mm": "MINOR ISSUES",
  "ko88t7mf": "MAJOR ISSUES",
  "iekoi9ve": "Net Value",
  "kru31dvl": "Date",
  "ujzajz87": "Net Value",
  "rkja9ftb": "Portfolio Value",
  "5a5e578w": "Amount Invested",
  "3cxv72l0": "Cash Available",
  "obobi365": "Performance",
  "our3nuo4": "Asset Class",
  "0vemdgda": "Currency",
  "ytnf6slz": "Health Alerts",
  "2uu2puwh": "Detail",
  "neadxzz8": "MINOR ISSUES",
  "0plh6q0q": "MAJOR ISSUES",
  "d8zszkbn": "POSITIONS",
  "position": "Positions",
  "u192lk22": "TRANSACTIONS",
  "5tqbxl7s": "Read",
  "0em7xr1j": "Scan  QR Code",
  "7gd5sfox": "If you cannot scan, please enter the following code manually",
  "smq78s7m": "Next",
  "eus8wc7h": "Profile",
  "wl1ownor": "Account Settings",
  "afxtmzhw": "CHANGE PASSWORD",
  "wvo4yj9k": "Change Language",
  "znd2aszb": "Switch to Dark Mode",
  "qhhwomg1": "Switch to Light Mode",
  "c0xbwwci": "LOGOUT",
  "k3na7l6v": "SELECT SECURITY",
  "cuaed5jd": "Type security name",
  "ogcb9xww": "Select",
  "2vhx2uhq": "Do you allow app to use your Camera to take a picture?",
  "1y3zn4oo": "Do you allow app to access to your Photo Library to upload use images on this device?",
  "7o5te87o": "Camera is required to take a picture from camera",
  "4xjp6sq7": "Gallery is required to upload image",
  "fphiwhqk": "Application need your permission to access to your device's photo library",
  "cvtkn5qk": "Do you allow app to use your Microphone to capture video?",
  "oxsqo115": "Camera permission is required to take a picture from camera",
};