var viMap={
  "3h41wkxj": "Đăng nhập",
  "c7folydq": "Trang chủ",
  "rf7r2nk0": "Đăng nhập",
  "g143uz7d": "Mật khẩu",
  "cais5tw0": "Email hoặc tên người dùng",
  "gs8awxej": "Đăng nhập vào",
  "no_security_found": "Không tìm thấy bảo mật",
  "no_doc_found": "Không tìm thấy tài liệu nào",
  "no_proposals_found": "Không tìm thấy đề xuất nào",
  "zlksaikw": "của bạn",
  "lex9mep0": "tài khoản",
  "d9hhr78b": "tài khoản",
  "e9zrlew0": "tài khoản",
  "zdbe1lx9": "tài khoản",
  "1tt86su5": "của bạn",
  "y8llhhe3": "Trang chủ",
  "r5la6ony": "tin tức BBC",
  "rog3ydmc": "@bbc",
  "y1dolub7": "Trang chủ",
  "4kyuvn3o": "Tải tài liệu lên",
  "him7gi6o": "Tài liệu",
  "lh2w6q42": "Lựa chọn",
  "mpbhr71m": ".",
  "jzvxxaxu": "Bấm để tải lên tài liệu của bạn",
  "mw4a4y0a": "Sự miêu tả",
  "alsw67uc": "Mô tả tài liệu",
  "3hz1whes": "Tải lên",
  "c7ypx4h2": "Trang chủ",
  "h66hylfo": "Thông báo",
  "dlkgtx0t": "Đề xuất",
  "lq59qmsn": "Lịch hẹn",
  "0lw6g9ud": "Nhập tin nhắn mới",
  "95k73u5g": "Trang chủ",
  "p1nsrsd1": "__",
  "yot02jf2": "Đổi mật khẩu",
  "510yg9y6": "Mật khẩu hiện tại",
  "729kp7ui": "Mật khẩu hiện tại của bạn",
  "ju5jgv6f": "Mật khẩu không hợp lệ",
  "2l6qayo4": "Mật khẩu mới",
  "oef8jq9l": "Mật khẩu mới",
  "gtihat6e": "Mật khẩu mới cần ít nhất 6 ký tự",
  "lz5cj3qp": "Xác nhận mật khẩu mới",
  "lph5tz72": "Xác nhận mật khẩu mới của bạn",
  "y6byl3gh": "Xác nhận mật khẩu mới phải khớp với mật khẩu mới",
  "iy4dy5qk": "Đổi mật khẩu",
  "nfc91a9j": "Trang chủ",
  "english": "Tiếng Anh",
  "arabic": "tiếng Ả Rập",
  "vietnamese": "Tiếng Việt",
  "12cgqet1": "Đề xuất",
  "j0hr735r": "Từ chối",
  "f8pf4flh": "Chấp nhận",
  "vhohm2gh": "Bị từ chối tại",
  "0gxshjqc": "Được chấp nhận tại",
  "lw93ftpw": "Trang chủ",
  "ytd2avxs": "Trang chủ",
  "57k3dgbt": "SVG",
  "f56350tm": "Trình biên dịch SVG",
  "yux64vyf": "Ví dụ 2",
  "m89f6pjw": "Chế độ xem tab 2",
  "0f4cc5jv": "Ví dụ 3",
  "ow2th2ka": "Chế độ xem tab 3",
  "7b4df5uj": "Tiêu đề trang",
  "m5iym6ry": "Trang chủ",
"j2jcor2x": "Trang chủ",
"preview": "Xem trước",
"fill_in": "Điền vào",
"download": "Tải xuống",
"signature": "Chữ ký",
"xptnvk4d": "Trang chủ",
"lvtq8f1d": "Loại giao dịch*",
"mzy7ssrc": "thay thế. Sự đầu tư",
"eq4x9n1u": "Tiên đặt cọc",
"cxoslr35": "Rút tiền mặt",
"ggeo4b0j": "Phí thanh toán bù trừ",
"z3seosat": "Trạng thái giao dịch*",
"u6kp9mh5": "Chưa giải quyết",
"mk5ongux": "Thực thi",
"h5kwz5n8": "Thất bại",
"airvu3wg": "Tiền tệ*",
"l0lwzjgx": "USD - Đô la Mỹ",
"1183o2jn": "VNĐ - Đồng Việt Nam",
"b2wletq2": "THB - Baht Thái",
"f52mzh01": "JPY - Yên Nhật",
"4ozeqrcz": "Tìm kiếm một mục...",
"cbvxrrgx": "Số lượng*",
"22c25jl6": "Số tiền phải lớn hơn 0",
"n2u1440v": "USD \$",
"wbwyrgib": "Tỉ lệ mở",
"oba6y3ps": "USD/USD",
"e0lclrlh": "Ngày Giao dịch*",
"b2ene7pk": "Ngày phải được chỉ định",
"l33tyaq2": "Ngày kế toán",
"580q4cpd": "Ngày giá trị",
"3gltw1as": "Thanh toán của khách hàng",
"8z8om63p": "Lựa chọn...",
"7qfeihe1": "su",
"dakksbhl": "TP.HCM",
"609fatzr": "Tìm kiếm một mục...",
"cmvhpvxy": "Giải quyết công ty",
"dsiy2ndn": "Lựa chọn...",
"e22smxml": "su",
"hlx823un": "TP.HCM",
"vrkibydv": "Tìm kiếm một mục...",
"ylem5knl": "Giải quyết môi giới/đối tác",
"ks86zlgi": "Lựa chọn...",
"yvdx9x5p": "su",
"cnko6piz": "TP.HCM",
"5zbutpiz": "Tìm kiếm một mục...",
"j9fxzxjx": "Ghi chú",
"zc9jp3sw": "Tạo báo cáo liên hệ",
"omnyycbo": "Tạo và lưu hóa đơn",
"qsuxqtdi": "Số hóa đơn",
"2gprp57y": "Đồng tiền hóa đơn",
"u9zuq2tq": "USD - Đô la Mỹ",
"2o1zdp3v": "VNĐ - Đồng Việt Nam",
"g4zhlylb": "THB - Baht Thái",
"oquoet9p": "JPY - Yên Nhật",
"cm03jx79": "Tìm kiếm một mục...",
"devm6cmv": "Thêm Phí/Thuế",
"w3yrqad9": "Tạo nên",
"rfeltbti": "Trang chủ",
  "z97rvm72": "Giao dịch mới",
  "ixctvaic": "Danh mục đầu tư",
  "53dk25lw": "Mua để mở",
  "6df6xxpt": "Mua để đóng",
  "81dcf4qa": "Bán để mở",
  "lzd9cyr1": "Bán để đóng",
  "cjuvvsm5": "Chuyển khoản đến",
  "zx1wc2ro": "Chuyển khoản đi",
  "m7418olr": "Tìm kiếm loại giao dịch",
  "rumkikc1": "Tên, ISIN, FIGI hoặc Mã",
  "dmgzjo53": "Tên chứng khoán phải được cung cấp",
  "whkrwls1": "Loại",
  "lmnve4ua": "Mua để mở",
  "kxq6qy7f": "Mua để đóng",
  "zrj8fd7n": "Bán để mở",
  "98cdg04u": "Bán để đóng",
  "isbfun57": "Chuyển khoản đến",
  "zswpadhe": "Chuyển khoản đi",
  "catj4e9j": "Tìm kiếm loại giao dịch",
  "7fx237xy": "Thời gian có hiệu lực",
  "f2fyvhfy": "Ngày phải được chỉ định",
  "2mpa9jiq": "Ghi chú",
  "u7hyldvt": "Loại đơn hàng",
  "2odrp5sn": "Số lượng",
  "lz424u11": "Giá hiện tại",
  "bhxqgsuw": "USD \$",
  "q9p7fv0r": "Giá giới hạn",
  "ee6858r7": "USD \$",
  "nbthbjny": "USD \$",
  "4noemhfd": "Số tiền",
  "n25ml3i7": "USD \$",
  "h2vfcolj": "GỬI ĐI",
  "7orhqoys": "Trang chủ",
  "dlgf18jl": "Tài liệu",
  "mg8sso38": "Ký",
  "5tjloy3c": "Bị từ chối vào",
  "rejected": "Bị từ chối",
  "ktrsz8sp": "Được chấp nhận vào",
  "9f0ag6b2": "Trang chủ",
  "fklubmeg": "Chuyển tiền",
  "pjltxv8v": "Loại chuyển khoản",
  "v2r1dlh4": "Chuyển khoản nội bộ",
  "trd84dis": "Chuyển khoản bên ngoài",
  "d5n27mwd": "Thanh toán ACH",
  "sut6gbhe": "Loại chuyển khoản",
  "ks1k9ld0": "Tài khoản",
  "at0kn69v": "Chọn tài khoản",
  "9h7dbdxv": "Tài khoản ****2010",
  "mo20dtfv": "Tài khoản ****2011",
  "m4lj06oh": "Tài khoản ****2012",
  "hg4nab9x": "Chọn tài khoản",
  "drpnsezr": "Số tiền",
  "mikxtr7z": "Số dư hiện tại của bạn:",
  "69029o9e": "\$7,630",
  "9vu9xcur": "Hoặc",
  "szvozgsg": "Quét thanh toán",
  "1mpq4mv4": "Gửi chuyển khoản",
  "umwc3lc6": "Trang chủ",
  "cnc2a7kn": "THAY ĐỔI NGÔN NGỮ",
  "yi7h9iqo": "Áp dụng",
  "tox2fkuw": "Trang chủ",
  "kls2a0ck": "Trang chủ",
  "ovw4ksp4": "Điều khoản dịch vụ",
  "sb815feb": "Chính sách bảo mật",
  "l6rxib8x": "Tôi đã đọc và đồng ý với ",
  "zfszy2xl": "Điều khoản dịch vụ",
  "x0c3ht3x": " và ",
  "lnywo5pe": "Chính sách bảo mật",
  "8lqdtz8h": "Chấp nhận",
  "vpe2dnt0": "Trang chủ",
  "nx64605t": "Trang chủ",
  "apuqhrbh": "Chọn bạn hành động.",
  "c4m8fcp2": "Từ chối",
  "e1wyk8ql": "Chấp nhận",
  "nkc71403": "Tên chứng khoán",
  "xc0jtpk9": "Trạng thái",
  "j72npzob": "Loại",
  "fyy6awn3": "Tên danh mục đầu tư",
  "qwicoekk": "Tên chứng khoán",
  "691qwpww": "Số lượng",
  "xopvpm3o": "Giá",
  "pgdm3cxj": "Số tiền",
  "yx8usjux": "Ngày giao dịch",
  "75vcm9jx": "Loại",
  "yow754bx": "Cố vấn",
  "c1i8ilcn": "Chúng tôi tin rằng bạn đang bị phân bổ quá nhiều vào GE và nên đa dạng hóa sang lĩnh vực công nghệ.",
  "y4rezelu": "BÌNH LUẬN BỔ SUNG TỪ CỐ VẤN",
  "1wdyw1a0": "Chúng tôi đã nhận được tin tức rằng GE sắp công bố một quý tồi tệ, vì vậy chúng tôi khuyên bạn nên bán vị trí của mình và mua thêm Apple",
  "99qsbuko": "Cập nhật cuối",
  "ke604v9b": "XEM TRƯỚC ĐỀ XUẤT",
  "prtogarh": "Tôi đã đọc tài liệu và đồng ý với các điều khoản của đề xuất",
  "decline_proposal": "Từ chối Đề Xuất?",
  "accept_proposal": "Chấp Nhận Đề Xuất?",
  "3esw1ind": "Chấp nhận",
  "a7lwigx2": "Đã từ chối vào",
  "uolmr1cx": "Đã chấp nhận vào",
  "s1juvlo2": "HOẶC",
  "fbk0uba7": "Gọi cố vấn của bạn",
  "pkkj5rta": "Trò chuyện với cố vấn của bạn",
  "chat": "Trò chuyện",
  "dperp1f4": "Đặt lịch hẹn",
  "mlj5814u": "ĐỀ XUẤT",
  "sd43hio2": "Đặt Lịch Hẹn",
  "rkobqzvw": "Trang chủ",
  "uak0wsex": "Danh mục",
  "eg1yw963": "Giao dịch",
  "1vddbh59": "TÀI LIỆU",
  "0po64aet": "Đề Xuất",
  "hello": "Xin chào! Tôi có thể giúp gì cho bạn?",
  "jmpup8vw": "Trang chủ",
  "u9g83xki": "Trang chủ",
  "mdc6xyu6": "Danh mục",
  "4ihsur3q": "Danh mục",
  "d33p2mgm": "Thị Trường",
  "khwv42ow": "Tài liệu",
  "wux5rc10": "Tài liệu",
  "5u97oz1q": "Đề Xuất",
  "6kq446fx": "Đề Xuất",
  "ran9xdwl": "PHỔ BIẾN",
  "lwqxf341": "Không có tin tức hôm nay",
  "gln3vyrv": "ĐƯỢC ĐỀ XUẤT",
  "more_products": "NHIỀU SẢN PHẨM HƠN",
  "life_plus": "Cuộc sống Plus",
  "mortgage": "Thế chấp",
  "mortgage_desc": "Tài chính công bằng của bạn mà không cần thương lượng",
  "life_plus_desc": "Bảo hiểm khuyết tật linh hoạt và tiết kiệm chi phí",
"vested_benefits": "Quyền lợi được giao",
  "vested_benefits_desc": "Đầu tư vào tài sản mang lại lợi ích trụ cột thứ 2",
  "g2rxi1c1": "Lựa chọn yêu thích",
  "yiyjkffh": "LÀM MỚI",
  "yj6g8w9q": "Kéo sang trái",
  "35ozpi3w": "Kéo sang phải",
  "pzvyvrig": "Danh mục",
  "l0x6h75l": "Không tìm thấy danh mục",
  "1ozb665k": "Không tìm thấy danh mục",
  "1ixt6js5": "Giao dịch",
  "n93guv4x": "Tất cả",
  "5xbdmla8": "Danh mục 1",
  "ojyp5aek": "Danh mục 2",
  "dmr0x7ur": "Danh mục 3",
  "uv5le3hr": "Tên danh mục",
  "u52470kh": "Không tìm thấy giao dịch",
  "449komyb": "Không tìm thấy giao dịch",
  "lt49c1mu": "Đề Xuất",
  "t7tz8m1x": "A-Z",
  "lkq0botg": "Z-A",
  "wdlmnbeh": "Mới nhất",
  "gxc8dzyc": "Cũ nhất",
  "r3f0hrjr": "Tìm kiếm một mục...",
  "93z66pdg": "Tài liệu",
  "0c3w378f": "Bị từ chối tại",
  "c64nnx2a": "Được chấp nhận tại",
  "b4bbsw9r": "Tài liệu",
  "gedmceci": "A-Z",
  "7ifi5rzq": "Z-A",
  "100mebqo": "Mới nhất",
  "f92uq3rg": "Cũ nhất",
  "h4estl7l": "Tìm kiếm một mục...",
  "qsv6jc1u": "Tải lên",
  "zu3zuhvo": "Xác nhận?",
  "s1jcpzx6": "Hủy bỏ",
  "bdc48oru": "Xác nhận",
  "tea2m5lq": "Tùy chỉnh",
  "e0dy1vxx": "Lợi tức đầu tư",
  "4kttzprb": "Tên",
  "6thwwafn": "ISIN",
  "ivu9tdzj": "Tiền tệ",
  "fbgy82bc": "Giá cuối",
  "swv2ctiz": "Giá vốn",
  "cdklrlbv": "Lợi tức đầu tư",
  "ox3fj6xq": "Số lượng",
  "juhk5a4f": "Số tiền",
  "xai3n31z": "Tùy chỉnh",
  "qhszshsn": "Vị thế tính đến",
  "zjpj3rb3": "A-Z",
  "qdw51x3q": "Z-A",
  "rp3i5rcp": "Mới nhất",
  "agree_checkbox": "Vui lòng kiểm tra ô chọn trước",
  "5dpmi95h": "Cũ nhất",
  "9j789sh8": "Tìm kiếm tài khoản",
  "yfas6pma": "Tùy chọn bộ lọc",
  "filter": "Bộ lọc",
  "sort": "Sắp xếp",
  "xccshnlg": "Tài khoản",
  "nhu5w9hh": "Tất cả tài khoản",
  "rfz2zg29": "Tài khoản 1",
  "e8wn77rc": "Tài khoản 2",
  "kwzaqasj": "Tài khoản 3",
  "ip67vees": "Tìm kiếm tài khoản",
  "bzc91fwt": "Tên danh mục",
  "oxhc1io0": "",
  "1mrmlye5": "",
  "4n2ah71g": "Loại",
  "date_in_range": "Ngày trong khoảng",
  "62i1ajo9": "Tất cả",
  "1bjf87l7": "Tài liệu",
  "6ihgprib": "Mẫu",
  "lhntzq4q": "Gói",
  "6b02yqcj": "Tìm kiếm một mục...",
  "wy8o7ldl": "Từ",
  "79c9j9tz": "Tùy chọn lọc",
  "uvch601w": "Cố vấn",
  "52i8slyz": "",
  "58gmka4m": "",
  "rvrrcr87": "Tên đề xuất",
  "3lusoo7q": "",
  "48bz3ofm": "",
  "tl67wc2i": "Loại",
  "ti52gke6": "Tất cả",
  "stsemzk4": "Mua mới",
  "6p82d124": "Gợi ý bán",
  "i76kvnmi": "Tìm kiếm loại đề xuất...",
  "7hue4ywl": "Từ",
  "lyqt7dgr": "Đến",
  "g7rr5vmv": "Xóa",
  "lmndaaco": "Áp dụng",
  "dx3hqly7": "Giao dịch tính đến",
  "prsblk0u": "Thị trường",
  "wzls4zjf": "Nhập tên tài sản",
  "7v8svtoq": "GIAO DỊCH MỚI",
  "new_transaction": "GIAO DỊCH MỚI",
  "1p01lh7n": "Loại tài sản",
  "q1rji7uu": "Tất cả",
  "0j3ikcyz": "Đầu tư thay thế",
  "2wib8de2": "Trái phiếu",
  "ub3zx1xd": "Hợp đồng chênh lệch",
  "47ohy39v": "Sưu tầm",
  "sotc1ho8": "Tìm kiếm loại tài sản",
  "zfneqwjq": "Ngành",
  "d63k4veh": "Tất cả",
  "hvikpfj5": "Công nghiệp",
  "dv5qr0ef": "Chăm sóc sức khỏe",
  "kwbxaj2d": "Dịch vụ tiêu dùng",
  "8f8r6kpl": "Dịch vụ công",
  "8ltvrr9u": "Tìm kiếm ngành",
  "nkjefkra": "Tiền tệ",
  "9kbotd9v": "Tất cả",
  "3wp2osm7": "AED - Dirham UAE",
  "dnclvhao": "USD - Đô la Mỹ",
  "2i05dwg2": "VND - Đồng Việt Nam",
  "ng4uvnyc": "Tìm kiếm tiền tệ",
  "jc3m5lbr": "Từ",
  "ww0vqchu": "Đến",
  "lafovd94": "Áp dụng",
  "fiha8uf5": "Trang chủ",
  "p38uhcf6": "Trang chủ",
  "xn2nrgyp": "Danh mục đầu tư",
  "new_order": "ĐƠN MỚI",
  "more": "Thêm",
  "a850huyh": "Danh mục đầu tư",
  "nkifu7jq": "Đề xuất",
  "32ibm5x3": "Đề xuất",
  "w5wtcpj4": "Hồ sơ",
  "e9g2ybjp": "Hồ sơ",
  "5pxwycp5": "Thông báo",
  "v9vw92bm": "Hồ sơ",
  "slptsuin": "Thị trường",
  "d696b0mg": "Giao dịch mới",
  "nqqw2mxy": "Chuyển khoản",
  "ba57jiqz": "Tải lên",
  "13mzcnly": "Tài liệu",
  "o5wm04m6": "THỊ TRƯỜNG",
  "t2nv4kvj": "TẢI LÊN",
  "acyeoaaw": "KIỂM TRA SỨC KHỎE DANH MỤC ĐẦU TƯ",
  "dxc8grzt": "Phù hợp",
  "3vkimctv": "Thích hợp",
  "2gjb3gie": "Xác minh đăng nhập",
  "4odbxp9t": "Vui lòng nhập mã để tiếp tục",
  "4jp9h6pq": "Vui lòng xác nhận rằng ứng dụng xác thực của bạn đang hoạt động bằng cách nhập mã được tạo dưới đây",
  "u6n47sl4": "Đang xác minh...",
  "v5jx3zzx": "Không nhận được mã nào?",
  "dumdc5yp": "Gửi lại",
  "efkolajb": "VẤN ĐỀ NHỎ",
  "05djgw4o": "VẤN ĐỀ LỚN",
  "834hxg71": "Chưa kiểm tra",
  "bwcpcgd0": "Các khoản đầu tư sau đây không phù hợp với kiến thức tài chính của bạn",
  "zz2ivcgu": "Không phát hiện vấn đề nào",
  "83o1ghax": "GIÁ TRỊ RÒNG",
  "hdgv1exn": "Ngày",
  "cm2ob3q4": "Giá trị ròng",
  "y6z0kvbz": "Giá trị danh mục đầu tư",
  "57fz6g1m": "Số tiền đã đầu tư",
  "rpfp7xvs": "Tiền mặt có sẵn",
  "zomhasya": "Hiệu suất",
  "7h0zeqv0": "Loại tài sản",
  "o00oeypg": "Tiền tệ",
  "6u2u1x9z": "Cảnh báo sức khỏe",
  "2um0eu09": "Chi tiết",
  "kc4yx2mm": "VẤN ĐỀ NHỎ",
  "ko88t7mf": "VẤN ĐỀ LỚN",
  "iekoi9ve": "Giá trị ròng",
  "kru31dvl": "Ngày",
  "ujzajz87": "Giá trị ròng",
  "rkja9ftb": "Giá trị danh mục đầu tư",
  "5a5e578w": "Số tiền đã đầu tư",
  "3cxv72l0": "Tiền mặt có sẵn",
  "obobi365": "Hiệu suất",
  "our3nuo4": "Loại tài sản",
  "0vemdgda": "Tiền tệ",
  "ytnf6slz": "Cảnh báo sức khỏe",
  "2uu2puwh": "Chi tiết",
  "neadxzz8": "VẤN ĐỀ NHỎ",
  "0plh6q0q": "VẤN ĐỀ LỚN",
  "d8zszkbn": "VỊ TRÍ",
  "7r8yq7mw": "trạng thái",
  "select_file": 'Chọn tệp',
  'capture_image': 'chụp ảnh',
  "position": "Vị trí",
  "acceptable_formats": "Formato no xe acetà",
  "transaction_created": "Giao dịch được tạo thành công.",
  "u192lk22": "GIAO DỊCH",
  "5tqbxl7s": "Đọc",
  "0em7xr1j": "Quét mã QR",
  "7gd5sfox": "Nếu bạn không thể quét, vui lòng nhập mã sau một cách thủ công",
  "smq78s7m": "Tiếp theo",
  "eus8wc7h": "Hồ sơ",
  "doc_not_found": "Không tìm thấy tài nguyên tài liệu",
  "want_to_logout": "Bạn có chắc chắn muốn đăng xuất không?",
  "portfolio_msg": "Vui lòng chọn danh mục đầu tư",
  "limit_price_msg": "Vui lòng nhập giá giới hạn",
  "group_By": "Nhập tên bảo mật",
  "name_isin": "Vui lòng chọn Tên, ISIN, FIGI hoặc Vé.",
  "wl1ownor": "Cài đặt tài khoản",
  "afxtmzhw": "Đổi mật khẩu",
  "communication_support": 'Mã ủy quyền 721864 để liên lạc hỗ trợ',
  "wvo4yj9k": "Thay đổi ngôn ngữ",
  "znd2aszb": "Chuyển sang chế độ tối",
  "qhhwomg1": "Chuyển sang chế độ sáng",
  "c0xbwwci": "Đăng xuất",
  "k3na7l6v": "SELECT SECURITY",
  "cuaed5jd": "Nhập tên bảo mật",
  "ogcb9xww": "Chọn",
  "2vhx2uhq": "Bạn có cho phép ứng dụng sử dụng Máy ảnh của bạn để chụp ảnh không?",
  "1y3zn4oo": "Bạn có cho phép ứng dụng truy cập vào Thư viện ảnh của mình để tải lên hình ảnh sử dụng trên thiết bị này không?",
  "7o5te87o": "Cần có máy ảnh để chụp ảnh từ máy ảnh",
  "4xjp6sq7": "Cần có thư viện để tải hình ảnh lên",
  "fphiwhqk": "Ứng dụng cần sự cho phép của bạn để truy cập vào thư viện ảnh trên thiết bị của bạn",
  "cvtkn5qk": "Bạn có cho phép ứng dụng sử dụng Micrô của mình để quay video không?",
  "oxsqo115": "Cần có sự cho phép của máy ảnh để chụp ảnh từ máy ảnh",
};